import 'package:flutter/material.dart';

class ParentLinkPlayerScreen extends StatefulWidget {
  const ParentLinkPlayerScreen({super.key});

  @override
  State<ParentLinkPlayerScreen> createState() => _ParentLinkPlayerScreenState();
}

class _ParentLinkPlayerScreenState extends State<ParentLinkPlayerScreen> {
  final _codeController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Link Child Profile')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Enter the 8-character parent linking code generated by the academy owner or player'),
            const SizedBox(height: 20),
            TextField(
              controller: _codeController,
              decoration: const InputDecoration(labelText: 'Linking Code (e.g. X1Y2Z3W4)'),
              maxLength: 8,
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                // Redeem code via redeem_parent_linking_code RPC and link parent
              },
              child: const Text('Redeem Code & Link Child'),
            ),
          ],
        ),
      ),
    );
  }
}

class ChildDetailScreen extends StatelessWidget {
  final String memberId;
  const ChildDetailScreen({super.key, required this.memberId});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Child Dashboard')),
      body: Center(
        child: Text('Child: $memberId Statistics and Attendance reports placeholder'),
      ),
    );
  }
}
